{
 "title": "TF",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "query": "test-load2" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Active_cnt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "active_runs_active_cnt", "legendFormat": "active_cnt" },
    { "expr": "all_runs_all_cnt", "legendFormat": "all_runs" },
    { "expr": "failed_runs_failed_cnt", "legendFormat": "failed_runs" }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_docker_containers_running_total",
     "legendFormat": "running_total"
    },
    { "expr": "node_docker_containers_total", "legendFormat": "containers_total" }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_load1{instance=~\"$host\"}[$interval]) or avg_over_time(node_load1{instance=~\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree{instance=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers{instance=~\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "max(node_memory_Cached{instance=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached{instance=~\"$host\",job=~\"rds-basic\"}) without (job)",
     "legendFormat": "Cached"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=~\"$host\"} - (node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk IO Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval])) / sum(rate(node_disk_reads_completed{instance=~\"$host\"}[$interval]))) or (sum(irate(node_disk_read_time_ms{instance=~\"$host\"}[5m])) / sum(irate(node_disk_reads_completed{instance=~\"$host\"}[5m])))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[$interval]) or avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[5m])",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "(sum(rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval])) / sum(rate(node_disk_writes_completed{instance=~\"$host\"}[$interval]))) or (sum(irate(node_disk_write_time_ms{instance=~\"$host\"}[5m])) / sum(irate(node_disk_writes_completed{instance=~\"$host\"}[5m])))\nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[5m]))",
     "legendFormat": "Write Latency"
    },
    {
     "expr": "(sum(rate(node_disk_read_time_ms{instance=~\"$host\"}[1h])) / sum(rate(node_disk_reads_completed{instance=~\"$host\"}[1h])))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[1h]) or avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[1h]) ",
     "legendFormat": "Avg Read Latency (1h)"
    },
    {
     "expr": "(sum(rate(node_disk_write_time_ms{instance=~\"$host\"}[1h])) / sum(rate(node_disk_writes_completed{instance=~\"$host\"}[1h]))) \nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[1h]))",
     "legendFormat": "Avg Write Latency (1h)"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Disk Reads (Page In)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "(rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024)",
     "legendFormat": "Disk Writes (Page Out)"
    },
    {
     "expr": "(rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}