basePath: /api/v1beta0
definitions:
  ApiErrorResponse:
    description: Common reponse for erroneous requests.
    properties:
      errors:
        items:
          $ref: '#/definitions/ApiMessage'
        readOnly: true
        type: array
      meta:
        $ref: '#/definitions/ApiMetaContainer'
        readOnly: true
      warnings:
        items:
          $ref: '#/definitions/ApiMessage'
        readOnly: true
        type: array
    x-usedIn:
    - /session/
  ApiMessage:
    properties:
      code:
        description: A machine-readable representation of the message.
        type: string
      message:
        description: A human-readable representation of the message.
        type: string
  ApiMetaContainer:
    properties:
      sample:
        description: Actual properties TBD.
        type: string
  ApiPagination:
    properties:
      first:
        readOnly: true
        type: string
      last:
        readOnly: true
        type: string
      next:
        readOnly: true
        type: string
      prev:
        readOnly: true
        type: string
  EnvironmentIdentity:
    properties:
      accountId:
        description: Account identifier.
        type: integer
      id:
        description: Unique identifier of a Environment object.
        readOnly: true
        type: integer
      name:
        description: Environment's name.
        readOnly: true
        type: string
    x-derived:
      $ref: '#/definitions/Environment'
    x-references:
      $ref: '#/definitions/Environment'
  UserIdentity:
    properties:
      email:
        description: Email address of an user
        format: email
        readOnly: true
        type: string
      environments:
        description: List of the Environments to which the current user has access.
        items:
          $ref: '#/definitions/EnvironmentIdentity'
        readOnly: true
        type: array
      fullName:
        description: User's full name.
        readOnly: true
        type: string
      id:
        description: Unique identifier for an User.
        readOnly: true
        type: integer
  UserIdentityDetailsResponse:
    properties:
      data:
        $ref: '#/definitions/UserIdentity'
        readOnly: true
      errors:
        items:
          $ref: '#/definitions/ApiMessage'
        readOnly: true
        type: array
      meta:
        $ref: '#/definitions/ApiMetaContainer'
        readOnly: true
      warnings:
        items:
          $ref: '#/definitions/ApiMessage'
        readOnly: true
        type: array
    x-derived:
      $ref: '#/definitions/UserIdentity'
    x-usedIn:
    - /session/
info:
  description: Manage Scalr Api system endpoints.
  title: Scalr Session API
  version: 1.0.0
paths:
  /session/:
    get:
      description: Retrieve detailed information about the current authenticated user.
      responses:
        200:
          description: The JSON representation of a UserIdentity object.
          schema:
            $ref: '#/definitions/UserIdentityDetailsResponse'
        400:
          description: A client-side error was made.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
          x-errorCodes:
          - description: The request was structurally incorrect, and was not understood
              by the API.
            name: InvalidStructure
          - description: The request was understood by the API, but included invalid
              data.
            name: InvalidValue
          - description: The request wasn't understood by the API.
            name: BadRequest
        401:
          description: The request was not authenticated.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
          x-errorCodes:
          - description: The request was not properly authenticated.
            name: BadAuthentication
        403:
          description: Insufficient permissions.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
          x-errorCodes:
          - description: This request should be made in a different Scope.
            name: ScopeViolation
          - description: You do not have the necessary permissions to perform this
              request.
            name: PermissionViolation
        404:
          description: Resource not found.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
          x-errorCodes:
          - description: This endpoint does not exist.
            name: EndpointNotFound
            noDoc: true
          - description: The object you are trying to access does not exist.
            name: ObjectNotFound
        409:
          description: Conflict with current state.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
          x-errorCodes:
          - description: These changes aren't possible while this object is in use.
            name: ObjectInUse
          - description: These changes would violate a policy.
            name: PolicyViolation
          - description: These changes would violate a unicity constraint.
            name: UnicityViolation
          - description: Some of the objects being changed are locked and cannot be
              changed.
            name: Locked
          - description: This Cloud platform is not enabled.
            name: NotEnabledPlatform
          - description: The Operating System does not match.
            name: OperatingSystemMismatch
          - description: Some of these settings cannot be applied, they either conflict
              with the current state or are invalid.
            name: UnacceptableObjectConfiguration
        422:
          description: This request was well-formed but was rejected due to semantic
            errors.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
          x-errorCodes:
          - description: Some of the configuration settings cannot be applied because
              they conflict with the current state.
            name: ConfigurationMismatch
        500:
          description: A server-side error occured.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        501:
          description: This feature is not implemented in Scalr.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        503:
          description: The service is currently unavailable.
          schema:
            $ref: '#/definitions/ApiErrorResponse'
      summary: get
produces:
- application/json
swagger: '2.0'
